language: r
warnings_are_errors: true
sudo: required

env:
  global:
    - PKG=DEV
    - PKG=STD
    - CRAN: https://cloud.r-project.org
    - RGL_USE_NULL: true

notifications:
  email:
    on_success: change
    on_failure: change

apt_packages:
  - freeglut3-dev
  - xvfb
  - xserver-xorg-core

r_packages:
  - covr

before_install:
  - if [[ "$PKG" == "DEV" ]]; then
      echo "Building development branch...";
      Rscript -e 'install.packages("devtools")';
    fi
  - if [[ "$PKG" == "STD" ]]; then
      echo "Building standard branch...";
    fi
  - echo "options(repos = c(CRAN='https://cloud.r-project.org'))" >> ~/.Rprofile

after_success:
  - Rscript -e 'library("covr");coveralls()'

after_failure:
  - Rscript -e 'devtools::load_all(); devtools::test()'
